// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/core/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9e3PbtrbvV8HhOTOxW0l+JO1tvaezr+s86tOkybYd75lbZ3cgEpKwTQIsAMpRc3w+",
	"+521AJCgROoV20la/pNYJPFaWPitB7AWPkSxzHIpmDA6OvoQ6XjCMop/Ho9GLDYseZ4yZuABTRJuuBQ0",
	"faNkzpThTEdHI5pq1osSpmPFc3gfHUWvBSMjKEekImbifqRMa0LHY8XG1DByw82EJGzKY0aoSAjP6JiR",
	"WBbCaDKSilBycvlsEPWiPGjvQ0Rdx55iUXxUb929IFwQM+G66knVi7GSRU58TWQ4w1665kZSZdRERxEX",
	"5tsnUS8ys5zZn2zMVHTbi0ZcJFyMGxp/w1Q/4WOmDfEf4UhXdQYa5oZlWOV/KTaKjqL/3KtmZ89Nzd5l",
	"kQqm6JCn3MxeQNFTwzLolOsmVYrOsJPQwi80Y4u9xEklGTM0oYYOBM1Yj7AsNzOkfMuUDSpaaKO4GJet",
	"wHeLrVyogpGbCXNDV/KGKJYrpmFAbuo1EdIQeSPsNFDbbtDSUMqUURHd3vYixX4vuGJJdPRrMLqwD70F",
	"9ggm611ZqRz+m8UGun+c80umNHZ4vv/Hb07dO5KwERdMI2Wm9hlLiJ0TIkdugH5wFCqAx1QQ29SAnDMF",
	"BYmeyCJNSCzFlClDFIvlWPA/yto0MRKbSakBLgKuU4KmZErTgvVwqWR0RhSDekkhghrwEz0gr6RihIuR",
	"PCITY3J9tLc35mZw/Z0ecAlMlRWCm9leLIVRfFgYqfRewqYs3dN83KcqnnDDYlMotkdz3sfOChiUHmTJ",
	"fyqmZaFipmGamCgymI/pAU3zCT3A6eDjiYlNCq2Vz9/NM08vet+H0v0pVcCBGqqp5uOyqrB6+NxXfSov",
	"g4rf98eyv8CaJ9TQVI5Xghd7T7M8xWVCA3ZoGUcvuuYiiY7K6nuRX0hQg8AFF7FkzPo0zzV0ROcsRvbi",
	"Ok/pzK7J6FkyZuQ4z1MeI8No5PE5sKux5zJcCBj51ndxnqF/5oCzmlBiiWQZpuJbeASsd/bs/IL4Wba8",
	"bdk4WL8VRwM3cjFiyiGckhnWwkSSSy4M/ohTzoQhuhhm3MBS+b1g2gCzD8gJFQACQ0aKPKGGJQNyKsgJ",
	"zVh6QjW7d34GxtF9IJluhLhwepdNwfRgyAw9+E3mTNCc//YaafaKGRoywbIaHEudw6dQxFBT6HUL2Y/n",
	"cTLgIMcWwYBcr5qA0dWKwmUz6R+UDPGeCkIrZieGZTlAnOUXSmJbakBODcmVnPKEgYwY0SI1gJYjPi6U",
	"LWphjpgJNSSmAhgnLrSRGYIgChzormPmWqMylDBfzFL7GKYMZmMLToRilhvvnq2OleEjGm+qXB4LQl1J",
	"otiIKSZiNiAXE0agNTLiLEXSA3kTDkUzLqgBjRJkZ6Et1Aj+e8Eq3YyVtWqSct3AIKJRlXqd236TSZFR",
	"0VeMJnSYYsuA9QRKOaUK2MG1gZLTi53oHyev/3lInnJ9TU5BC26ab/tg7UnzxL2AYre9qFC8QcHxdHx7",
	"doqUkIXx6g35vaApH3GmLG3945LkZMfQMWiyVt3dRW6HtcYSQg3ydFrYVcczVh/w7wWdAXQrlkyo2VMT",
	"lvaHUpq4/3ssbw6Bl7h4ycTYTKKjgwVqzPEivrVDXJPlLhwxW8hhLYA68wzIq3U5h5yKOC0Av+yY0LLp",
	"DwueJkwRWZi88G3UVCgQX5QLpqJe5OlAMw6WgZbwt6CxFAnt25/TLLmG/yaw9hS9iXrROGZAgorQYZVr",
	"aF8tpDoJamn55B+uvy2vj3EYLS9PcThtJd2gl350aUnR9hYp1PLyDAnX8vIF0LPOQifUsLFUM8s+KJ7A",
	"6KqETNQgD7EEGgRezhEw9sLJ1zMNorZXq+rdprPm2zr3tTW8Ow4bmBucl7PDtGF9nNSkMOJsXQoD6gNk",
	"IADAAEkKShjZoaUo17uIwnLKlOJJAqK6ghz8ekCcYOnbwk7aj4o0BasnT2nMsPL6+x1QITOmxizZXcRu",
	"q0C0SxqjikU9pknp2GFiekmV7pFcKqN7ZCrTImO6Vwpx3SPMxIPdGuJ9iFw5+PPl6xe/vXx2+ewlOhVG",
	"EkAKa4PJ/H7/+/0j+AfnZgHM7EDOEfA3G85/n7/+hdiC1pwFFSQOJpzkVNGMGdDpYY7MhHEF4+YJkiBQ",
	"Q6r+gLxrEotPmaE8ZQlJZFxk3ibukRzlBx2mYDOQjKrrRN4Ih4YNis7tckB/CkqS4+XN1IigJJoW0D6y",
	"NXqewlUKMs5x6IC8QZ0MOFAksIhQSbU1gQmPOvgi+2VMa5DrC2Q6c2KMuC8Ie5+n1M7NzWRmlQZeawOm",
	"5gYWnZEkkYQLbRhN6vL1AotB32tlB+StZkSMuXjfz9NCh4UXFA631GDulmg9qN6gA4SRoESdgDvBcpUi",
	"ndXXRlR1KFol6j0hV8j5l1yb7a0WKG11dxDnMLrgpb47y6H099V78rKl0bXcg6HZ1uAT7PwCn4FfACbY",
	"2mKbGVWWAVawPlYMTJmmr0fR0a8f4bL4MC9EK3/anKMXJtIteFNCz5ClUoztVJ7zjKdUAWah2pKjEBfk",
	"52LIlGDG+RJLSKjcZ6sQwXdqkSzv5pf4K0dKxPi6l8I7NMmz94aJRJOKEHajwg9PxzLnYtwoC+dt5q0B",
	"CErXXM51/8eiiGrAJG+SLDFzrBaA7F5ZqLVqyVPsREKkiNnfFm1Abc28KSOMxpPKLuciYTkTCRMmnQ0I",
	"qNJLDG9vbpfT/+sHT9zQfkETtjQdcyUzZias0MGfOOmb4mTph7hFs/PUFj9YBM84UP3XrLu0Fm573lrY",
	"pGs1fRyrqKk7a9YSKklQSeiFnmeOn5Z4MfQEVDUuSh6BieNi3IyONcXvrUqbBJ24BkRg790WR61IY6UT",
	"mbG8UZMCDPJvyduzl+VGVk0TyZXE7ZimunnctAkEVUlFEDfenp16XadWK5TE9jy5uCBvTxsbca5N1bBz",
	"6N5Aa3kxTLmewI+G5nZguqmY4e4qoxnOzm5jc3oilXkatrOABmSoOBsRKVg/5YKR4HVT683NFDkYMO1T",
	"7D6okBZpGk430m/MDCobE5bmgzvwgnnvlwOuJjCcUp4iq/tvSKGhCydcxFwIajjJZAJmKejOTsW1eJkr",
	"nlE1IyCsekRf81xb77M2WGM8oUKw1L3BjbyMJZyaqrF52HNF0BK0tUS9aES1AflWwa4zaR00HkV6Qg+/",
	"+faIPmbJ99/ElA33D0cj9u13cZJ8P0q+e/Jk/9tvv9un7PvHybePH8fDg2+fHB4m+/vsO/p/4sPD77/5",
	"Zvjk2+RJoPbr6Cg6HDx5MtiPehEOALp0OHjyeLAPfZmWu2SHgyffDPZRXQh7v7rTU1f/QqOPsdFaC/jd",
	"FtgeaNt1NG92IVZSM+CZFQpXsy8RRZ4c1Reuk3mg6HpZErqApN2tVtkNVdCbRPEpSr5QCk5YmkU9EINJ",
	"ygy+zHKp8XtQEzd2GUFPX59HC2N6XnVk7s1T36+55y1uQnj1k+313NN/lINYqMmPab5pHGJ9AgLbaz2l",
	"t13ALmi8JUMv+MLcG6s0ecUoUHlDg23RclimZtyJkK8vu2Y19MNyL/uC+kxzdGF6JQ93W4x0B3dqmwED",
	"8jObaavyZdSAamg/5wKdhINyoQ3Ia5HOyDWbsSTwo1PFCC2huVROvRum7lq7DyT0HngLUxbggFwh/Q4a",
	"/WEeydblxnPk4AZzBTQaEEWVbHImt6jkUK9y5YGg9hKpyMeKJgwl0wAF9DXPz6iwitMm/bKFFjt3zrIp",
	"U0TBa+CKUnqW/mDfh4QrFpt0Zs+12P5bYQrT+kdfGwU6jDXxUS+YSDPi7+dNwqtif/8x++FgsD/YJ/gj",
	"Phg8thPjBNSCcC/Zfqv+rSnLQdL1JXBxs1SPsMtRLzoYHFjhuZYU83yxCBDTTQGvlcXOWUaF4XHJYBxM",
	"Ntz1IztsMB70yMHgcPC4Rw5hDH0VH+wOSOm0HFWeUSJVwtB3REVS0nasaD6pT6NfTXMCeFr6PUrMrYHY",
	"Gub9cdWX+Y0WMpJpKm/8MpnX7WCmVaWUXQmAHyETe4gw4BUcD47Q9xKRKqVD+BMXqNSu6OBKvA2Wof0y",
	"cfb0cFapkjt2ke96FXInK1LDc3wi1ZUo1y7Z0cGq2w32GVskWrhHcyXcnktt88TbpIMrscSjsb07tdWV",
	"+uBu1I1dqJ379K/mPt3eaeccdvBm2OiyCxFpULIkQkKpvVijMpUxTdNZP6OCjlmyYuvhgXw527lGHswr",
	"8qkcIp/SF7JkY/S8PDa4BSdj2fDcHo63UApxxr6tyVc7iMYtd9t4k/UU1MfmZ7OqcC24noeHE9/uSqM/",
	"6GEjKkzZCUYj/Dg7Z1OmuJltSlMbzCBHsAQMF7EhJ5fPXGQCI1KNQRGY8PGEaUO0a6SBlIobHtO06UhG",
	"IUy9AfcttrRmOAP0YJ26f+LjySb1pvJmnWpfyptNagW9u8jWqfgVfrlJ3UIKthaVYRpxY0hI3LOX3NoJ",
	"PMvBNt45uTw/JzoGCbu/u2bjRpqmOb6Ax3NN01hJrT0XrVl/Ia6FvBGbjc8VAowqBA4oqXHqynbnPW04",
	"yF7F0479ynm1bOOmoup00wq1MR53v0h9aEoZIFQt2B4ZFvE1c1FDLrSkJAjZ+bfkKCV8FUaSaRix85uP",
	"RtndZJn7kKYbNC/mAaPsBtfE1/FRK3/95uDdx4DB+i2l8uYj8WH9tmwNHwUZ6zcG5T8OIJ7O8y0uXGpI",
	"yijYQAIsUtEX0vxWcnTZAYFb2uxjIWT98boqPg/sqEXTnRdZRtXsjOlcCs02xBEPP0Tbatw2vfPg2am5",
	"Q6M3a9wFxePjwRlttBpdkKU7nEaOh6DY+cA83zUyocCLRDGRMAD51+fWs9tsEMCbp+jrbeuEj4K8px40",
	"m+Jn3rqG138jNL2hM03a57pFg8d3G0Vi+tl39a5lm/p2mtgTIzSbery+1295/3ormLvOpvbQhp1wvQSB",
	"eDD1msihZmpayc8y8mbThV9vfg1foA1wrUlegugBynecFghG7iSKY1SMPB4spf29IMODhCM1r4vWgX7M",
	"smjn3I9dE86NvTC4bbzYNZ80voUZoMYwBVX+a2f/f3496H//7uoq+Wr36mqw9PfO34/6Ozt/Pwqe/Q/8",
	"8yvt/3Hc/3/9d7/u97/3f+PnUMPa3+9+tbv7dyz09U745mtbUe0RfvtfjdEeTSGy4SZPE12rPZ5YCm0U",
	"5cJ4mjZsyCB9dwfkPKcx62uWU4Vnlg1Tme7ZQ2KonEh/fhhYHmOzdlx1rt7Y/8H8gx75oUf+t0f+teu8",
	"+T5ivGlTMGrrXH2Wf3Wf2Q/+91/vvgJivvvaUfXd1zvlX7t/3+lXlB708cnV1dcLz8g9VLr71QZTuo33",
	"x7l90ImtmCmUC3hAqIppmrqNs0SKR8Z/IQ364nB93qE/P5ZJEzMWY4BplpCfLi7e+C7At9X2sNUvemSf",
	"8BHmFdCL4ubxYaNi23n279Sz3xLucLwQJbnoW618jJaOCBBt5wEVo7rZiZvReMIFa22qjK4oG4CJdorK",
	"VfSc8rRQ7CoqldZT1yHLAly7fBkGtw7RjqvFkZSnFwbkmJxhN0mcUgViCYOhkY3dYJGNhwWsL58Ro9qs",
	"axbG5SpvXMiOlhXxyGvBiBwdkavovIhjpvVVRKQKR3rvbKNzFvepSPpVmMzys92NCoIduIOJkgN6S0ND",
	"aurIpvHG5SGMmja5c3L5bNfbtQMStsDdZu84lUPriMU0Hypxa/1CFdrw0exvMEczYjebDTFMUGH6NhdK",
	"cCT9Ap7HMxvKA5LU7yAHppNPKIO7Sew9QIiSxXhCbiY8nlTt/F4wxVnSANbJlGupZqcNKHjJRAIaq/sk",
	"VK9ssH3J6k2cujpfT6vbbeiW6MnlswF5LpUfbTVIGx3l1NmDv6EoqBOCGx8LLopsaPeOkjBDkE9VpAoh",
	"7PkFZ8WgouLbt1VLNe7fwKpcrB3Nh9AvezOR6Sbe2a3F5ZQ1TRpw3bweDAPpH+4fPukfHD5+0rxBFk+1",
	"Po+lanKDX56fkyHVzDm2Fye/HOYoldRU1VvSLxwpWwCviVSmtJIchtWWXbszYrUvZMfGqiny9uzlbiV1",
	"6zy1jbcjK7zvf97vsWb9D6F8HNs1crmSmn6XNTk2TSeqHAa4rzC23zLColcPVJM+fNAowAJvfb2NX6B8",
	"alMiecsZT9iEZ2VPKhfgT9YF+Mq7AF+iC/AX6wJ8u+AC3EDW2KUV9HWlbMGEXBsLGFirmAWMJR5BpEBW",
	"zVAiA1/pHqHaqb1u8wFgq4/eWxsVWqJTXVLhyRuvW+oBeQZWmHfIBhu90KRlYS4quYGdu6FW9gAq26NC",
	"G+Zkm9vDWob0/pT0Jm7pzwQ7N0sLV5otwaCB4CCjZ9Xw7zgr3B1iTTOovPDp7BbNAvr+pF26/OT2DOal",
	"jFsQNE1L0q0najL6/s0yLHtpE6zRRkhb1eqW2PZPqcJtkYZWyrSFZVrATwt5K/LntTDelio2rASPTM5J",
	"alNKxDXh2gucuEA77iW981L4oEQ80YuJXPBQ+uek9P7SpIzimi8VUeSCqutrwOAXqLuNuNLmnDHRtEL/",
	"WeaO9EIIP5/bV2im0tIFuoVC164YnrGRXql9BpshJe47gbAG9LfEwVWo/smVtnKPw/ttcCnXR3qvYBZO",
	"aQ2+qjlaD7+2OOz8ho65QEe3P+W8WG1w3G+nprkFZuXuvR+Krnq6tIflxOVu+3VLJeTTKSAvecuS/XxO",
	"Hdc6feq4dEPOOyutWyMJFeT1OfDTjVTXqaQ+p/LQnfkFG6FVFK6bVbkmndh7OrfpG6JZTu0hT5RqO2Xm",
	"42FKtSGKJrzApMDrHo/bxswf3B/6N+FPVK98jVnPN0+A+GNIv9pWMmCuUymR2jaPU5XJ2akad7hVs5b9",
	"VKJJfebdZnrzFLXAF1P9hgzaSt7opfnE14awetbztdGreXu9Yarvxy4qzWh38OJh7aOlrS9VJz4ei7ez",
	"tZp6/KBWViAfGgyuNUXG3SsqpJbZ+1MoInerg3yqEK4mreRLU0jmD4xtxmjW31f3Q7qrHYaz4Fiov2yg",
	"SFMga5Hinr1N5oghtWH0CTDC7lbREWVQxPyB1GoPqN6DuwmcwHiJO25yeUzFS3lz1w2uDLdwURZ33OyK",
	"SIza5RoPFoQxnd/lrWSKGz4vkWvbga+O0qiP/XMO0LjDQ5TPMFasaX/D+5wqVe/OlNu5qJKlUcMN0WIf",
	"oy+2n8Rcz4sb9qNpatrD5rZOHlhW8SPVTdlU1kne1FqnTeXUlLZnjePAZS0+2ha3syhP7WKVghGqcxDj",
	"PhZxMUCRa3L85pT4qRssJSJSYGHa4Skpow5B1SjwsEyQnqBKiIithSdobE4KDO2A6UGLP0lCHzmmWAFF",
	"dnERgOV1oajQlpg8a0mhhhYaavguiNn11ZRlWWL3toFo7vgS+h7wNOAmun/LGTGMWiblsS2fGNfl2wUa",
	"+amjQ1kY1+Oye406lve9vmDCHYhqHv2gvBJpXH5ptxDq1LihGvUUMMcSUuRSrAnu7efVdjDqeJfYL6rs",
	"db7NR3qtka53ZUgr37ZcIlIeumpgozWPYK1qcsVJtpIOPbs1PiIXqmA98hxlBXlbBRV5Qw7eR70IP1hm",
	"rzXnx6r3ztU199RXPfe4bGnZqFdkDSs5jYfnOoPRHee5klMGYH/x5tUlw3OFCd6VVL54yoR99hxTcS9+",
	"iucAuU0yV/vhQe4NVRo/PZ+JGP+4pCmH/88AsQpzKt4oOVb26q23eYILFL7PWew/feXSmby+EUzpyIde",
	"PWWxzDKuQXJBofUm5plQMk0zJsyZPREbjHfhXX24J4CGI0zafc7H0OZiFa3flLRs/aIkcusX9e6csVxq",
	"bqSaNZIeKN76YmF+wpflXNlIDDcL+KNp1uxsBHNnH4QzaJ+sO48NbF/aqo1ZWjDLbpU9w2OwBV49E2bC",
	"DI8D1wDmFZvQKQs3glOuncNzShWXhS5PErsD6uS4stwzOsMKrJHpEOVDlfS3R3zHbhszGxguiob1+4rO",
	"8B4EZgi3uFVopvA3JSnPuLFJgsLDiGiPlwd77AVvVXL5UvigAFMYI4eHgpBCwSFjvKPFH02WOf29YOVd",
	"cUPsR4LJ2rTGF/bsvjtV7q+cCw6gA+XtdiVqPuguMhK6qTibWu1AsPfWXJejIFlbSe4TSybcpMfwEa4N",
	"6FRYF3TLnWHPpeVxTzI30noCFRh3PKFibHfMkARmQgWhZMRuSMZFAeTCOc2p1iyxJPEz7i/ys7cDlceo",
	"cBPUJvy02Y/d1DpS3vA0hS5aZ3ZMU08pR2ln4OKmtPdn90gh0Cs9k4Xtj2Ix4yUpjbxmwt16JQhTCoZj",
	"BWfLEffMXghgszsVTen4L2ocpYuhhokVxjFXkGfZHezyZ47t8gl20vGb0jVvD70z/9Qyi09Yk9hTeeiK",
	"R6pqlrLYSKV7UGiez8tx+E6VocD+tglXjSd6ykYGTFpYPCIhMuMGfbaFsiH3itOU/+GOt4cdxXnM8pQZ",
	"RnYYR04fspgWmrkDuzD0eFKIa6hJVm/9gWLjNWH8aLcaj2KOdJYD58dkB8L1x4zER4lIvC0IeXx6MDj4",
	"hiTSx7QEbVguBw1TwDTCIMrbGOb5Bkb2FdOGZwj1X9nVxv9gLqGLTGH+sBMnGH1S3lYJ7SqGSNlWt5Ee",
	"+aRyP3B3cF0XxEqFMUhNv3gdRZWtnc8LEJqmJIfVj8FDjULErgnus6lBCYdiiN/u21gxdwnqnH9BCGlo",
	"memmLdfmiuya1cfWspiVWOjixhevgoH+OC1cG5rlzbhQGnPOUQ22ix1Ksr61lrCUbdOWWwBYfJP2xksM",
	"tWNi0S0u0aXmpg/s4cCIc4siYRozF6JdPyBvZF6kNLgC2N7CNCBnjCaY03FdryxmAFyaapW+96lWv328",
	"bq5VtxlxzWZes1m4+dALdqnGVMBaxuyENrsw/Nyx2+/w1OLzbhixt8BUzZfcoXwJbnpxl9pGvXBYh980",
	"jUveiKaY3eNwF4XiDcDa36Jrn4NuR67Qo7UHbV9F7bcEgZSsyfmGBoXXihxRsdlyl1oHqscjHdy6G6SU",
	"FMG418jGNQ9gb6iJJ84UgP6V+1kbxOHLloVXBbEZCWgHlArNRZrgJXE25ST+lckprrz6OYUgDICaSdO0",
	"4TVSbyQSiMBHjdOBjNrcVas6OeeVVD4P5mDB6SDzyHWjyZ+wkNlLs7jADat4wjJLrSGjiqnjwo7E/nru",
	"F/N///Mi6tkbz/GeaXxbjWViDB5fkmrcdMQBRvL27enTckXY5Rd4jBxHs+C00iuaO2dZ7Xtdv4kb9zoF",
	"XnXB1CzyaxJ68huaY37oOf+Zwdhve/YaMZ8K2Z4oARGdRkeRYTT7v+FVxlWNMAh7ozIq60qm5ILRDO/a",
	"SB0N9NHeXq30Alb9Wq/i3U5TsV23u2rlmU0LyOKUAtdOwR4TdGxvjpIjf3hFjjBzahUtUF5K5g846cGV",
	"uBIX3jfrF+uOv6x5t/L34oO+NvawkFcCrIagGOjMKLGMdGaGDXNIeczcXoWj2XFO4wkjhxhKXifTzc3N",
	"gOLrgVTjPVdW7708PXn2y/mz/uFgfzAxWYrsyw3Gqc+R//jNaS31fXnrNHCixZHoKHo82B8cuMWBjL7n",
	"cueVkDJmpiUjaphPMty/CtOklmgCnI/FjtM0LIht+8vicJ+gAWxdhH/5IdDWHnB1urMuUhOEP1vwDS1Z",
	"t7aqGoKE4mb+q0fednvkr4B1p9AUm6I7oG7atCyy0rZ30EAbVLfbXpNKYm0fayTDl7GpLBI0f5zJ6TVL",
	"q3Fw5bIH4107mIsXr0SZMjUzE3fTUFNHsdS5a/UBe2tTCvd8Fks0oFwOByDxNSOPfnjUI49+gH9hxT76",
	"jx8elSkjoms2O/gB5+2gd81mh/9hfxxeRbttI8UWtxspsFJG3/OsyGqWqOW8cpChfVzZvheVLwL1WGt4",
	"tTNarTjhozqbs/d4NeyF9WWHToaMzqx9Wb9BUwd8zwVgZ2XWI4VaOYNn3NTotJD/wNEkOjrY39/HvPb2",
	"536DaYZ3eNhBIbQc7u97SeOuBgxuLN37t9veqBpf8/4CPM2EsmzOtPsZsO/JHTZa7nEstPUjTYhX0LDR",
	"gwdo9K2ghZmgsp7YVh8/QKvPpRri/avY5OH3D9DkhZTkFRUzT2INTX/zIKM9d2rHW1H6Ka3OTse6donc",
	"bS963/fqAYiDUK7e9kpBu56QrZ+nW5SqXuZ+AnHaSdNOmnbS9E8pTTtJ2knSz0KS5rIpwOYEfc+ELgjJ",
	"RRlpP/X3cVjvENPmR5nM7nrR2LFW7iejCna7sFYP7qfZJgIl6H0Q19hyjRA+wLpOq3jhk7pSEVzfCx1z",
	"sDyUyew/97z7Cf2sOJ1P0WF/Ul34W28sqb2eb8gh5+pWXjDT2sS4encH9VeHjNpaOfdHnLZsK9DnTr0X",
	"pt5WOv/Fx0zQmfWatpJP1d9vPax6O21kVE1fbdnmbSek7ltI7T+EkDqRYpRy66zvxOIKA7NuXO59cH/d",
	"7m3q0bXnSvyzpWbnWp7c+Z2/JqHdfG07KtO4fVOZgzVJXgnazeytjzCGPzsz9e7N0Y8x0jqHYidh7kjC",
	"PHmAJn+RhjyXhUg6EbOV5XWKd9eLZeLiZIVV8fnJi3f3aibarGoNfFENFalaHW6RwbmxBzcv27rbYGLW",
	"LL5mEzNZ+GSpBYOTMMAjItVEbmG7NXdmXH9/jz2pm0DNvVGL39xbjzoD6c8ovh7cJvtCDKO9xb23efNo",
	"7wOsjFsr8ACimrIX4WnwuuhbZSs9XYF3X4Cx1NKjmowaNLeP/20see9Jr29nsE6d/1Pi4eeHTo0OmBcY",
	"2bUJqLxYprd0iPJgiLJCQ+5gpYOVhzHVqYknTfmxTDzZyFTHEn96aMH4BhjpnWLMuv6CPjb99WZ8sjQO",
	"ZK1t5w71OtTrjMuPxNnCNOVhQrfNRjh7tsrV0ylxn7lDtow4++yQ9xO4gDu87/D+r+1M3Nh5uOTE4tMl",
	"B+M2lguAVbZPnYuuQ5kOZbo9/s38kUtw6kXb6dqtQGpsk9t+IS6/DqK6Q0F/yUNBa3kal4BG6GG8C9jo",
	"/HgdlHVQ1mlbXwR4NrkPMWnqeobh2bJ4nK3Qs8DGvwwv3WcHjw8cytcBcgfIHSA/eBQVevb2qpT4rSaz",
	"LnPNb2Y8N0Y6brX/09nOHb51tvOXaTtvhh6hFf0Z4kdnQneI1iHaX9ug3QzQzlYnf/gyIO3LN2s7yOqM",
	"zM7IfAgjc+4m0OUZOhKuDRexabs/1CUQd5f7lZdT27vMq2stFzN5XM71okvL/BdNzfgcSWsk0VKZuftR",
	"PYFxWoetiQ6h5I+zWrOJzaEJL6vbyf2VAsGjuLy9HvSK6kp5f7t50x3pC9f9QcelSpgq7z50fW7Ph58w",
	"1dJfqDu8/gB/4cN1+tIluvy8s7zULsp9oWSRtyd7GXwSvWjwaRSjwSfQjAafUGsYWLXh4IHUstMsT/GS",
	"CpaQnTrIjhjFm3zd5WJMgF6R2PuyuHaAsDv4pGrOoKbn1Pq/qO3MKzgNSs9ePGV67wNi/O2evXS9VRE6",
	"Q9QkOVN9vN4DRSb+hZflDfG6NUUTXtg7mSk5uXxW3c+jGt3wNSA4tR1Yw/Ks10x2oD0XgNGDl/3D/cMn",
	"/YPDx092B/5q2aCAJtpwvNodh3S4v+80N0FYlpuZHUzfDcbdulfeH4ccYrUlvMyYGtpi7Vrh+cmSpXUa",
	"35ej8dWWj5I3Wyt63vqwd7vqUIdaeIOr9xeotFPwOgXv3hQ8h+uddtdpd5+9dne3+pW7+CwIUWr3MS24",
	"lhCu3YWYXIxTf48ayDv3V3lRqr92bkHBsmC/oZsJ0TW80c5rBra2O3fyd1pP5+fq/FydGvTnVoM6F9cn",
	"VoIedvevU7w+G8VrTxdZRtVslW/LahFWWhBXxvmy6hrYDTcTWRgyYs4JBCVHRZqiZwqAck1lbHbuevbZ",
	"a2R/Vg3lPuG/fb7PXJOdPOjkQScP7l8e2AvJt7PDx2PFxhTGYkWB3f0Yztwfq23w5/DdXZngWFlngXcW",
	"eGeBdxZ4Z4F3J006tatTu74ItevurHCreG1phC9oYx9tgz+UStaZ4JuvmNbZ7izwThR0ouDhRMGa4C/V",
	"uH/DE3vEz0ZOAIh5ebD6EGEF5g+jU3Zw0p1y+Sst7dteZOuxKlKh0ugo2qM535seRCDKXcXz6/u1X7Ua",
	"+jMfLoqW+1yC9EUNKKgD9MH64BUDxUaj8lKiiEUdXqu/PuLbd7f/PwAA///Twtm0RQ8BAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(path.Dir(pathToFile), "../v1beta1/openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
